-- Fanta W2D schema (malus only)

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text not null,
  password_text text,
  password_hash text,
  email text,
  role text not null default 'user' check (role in ('user', 'admin')),
  balance numeric(10,2) not null default 0,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.malus_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  amount numeric(10,2) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_malus_rules (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  malus_type_id bigint not null references public.malus_types(id) on delete cascade,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  created_by bigint not null references public.users(id) on delete cascade,
  malus_type_id bigint not null references public.malus_types(id) on delete restrict,
  amount numeric(10,2) not null,
  description text not null,
  cancelled boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_transactions_user_id on public.transactions(user_id);
create index if not exists idx_transactions_created_by on public.transactions(created_by);
create index if not exists idx_rules_user_id on public.user_malus_rules(user_id);

create table if not exists public.proposals (
  id bigint generated by default as identity primary key,
  proposer_name text not null,
  target_name text not null,
  description text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.proposal_votes (
  id bigint generated by default as identity primary key,
  proposal_id bigint not null references public.proposals(id) on delete cascade,
  voter_name text not null,
  voter_name_lower text not null,
  created_at timestamptz not null default now(),
  unique (proposal_id, voter_name_lower)
);

create index if not exists idx_proposal_votes_proposal_id on public.proposal_votes(proposal_id);

alter table public.proposals enable row level security;
alter table public.proposal_votes enable row level security;

do $$ begin
  create policy "Public read proposals" on public.proposals
    for select using (true);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "Public insert proposals" on public.proposals
    for insert with check (true);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "Public read votes" on public.proposal_votes
    for select using (true);
exception when duplicate_object then null;
end $$;

do $$ begin
  create policy "Public insert votes" on public.proposal_votes
    for insert with check (true);
exception when duplicate_object then null;
end $$;

-- Seed data
insert into public.malus_types (code, name, amount)
values
  ('malus-1', 'Malus #1', 0.50),
  ('malus-2', 'Malus #2', 1.00),
  ('malus-3', 'Extra Malus', 2.00)
on conflict (code) do nothing;

insert into public.users (username, display_name, password_text, email, role, is_hidden)
values ('admin', 'Administrator', 'admin123', null, 'admin', true)
on conflict (username) do nothing;

alter table public.users add column if not exists password_text text;
alter table public.users add column if not exists is_hidden boolean not null default false;
